### ISSUE TITLE
How do you run this on windows?

### ISSUE THREAD

**Issue by brendankehoe** [grosser/language_sniffer#4]
I have installed it after some bother. I haven't used ruby on this computer before :) I have tried running ruby language_sniffer in bin and ruby language_sniffer.rb in lib to no avail. Errors below. Thanks very much. Brendan

C:\Users\aa\Documents\repositories\github\language\language_sniffer\bin>ruby language_sniffer
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- lan
guage_sniffer/file_blob (LoadError)
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from language_sniffer:3:in `<main>'

C:\Users\aa\Documents\repositories\github\language\language_sniffer\bin>cd ../lib

C:\Users\aa\Documents\repositories\github\language\language_sniffer\lib>ls
language_sniffer  language_sniffer.rb

C:\Users\aa\Documents\repositories\github\language\language_sniffer\lib>ruby language_sniffer.rb
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- lan
guage_sniffer/blob_helper (LoadError)
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from language_sniffer.rb:1:in `<main>'

C:\Users\aa\Documents\repositories\github\language\language_sniffer\lib>

**Comment by grosser** [comment]
`ruby -Ilib bin/language_sniffer` might work ... ideally `gem install language_sniffer` and then use it via the commandline ...

**Comment by brendankehoe** [comment]
Thanks very much Michael for replying so fast. Much appreciated. `language_sniffer` is now recognised in `cmd.exe`. Using Process Monitor I can see `C:\Ruby21-x64\bin\language_sniffer.bat` is the file that gets run when I type `language_sniffer` and press enter in `cmd.exe`. It turns out the language is undetected for the code I want to identify. :) (code in [this blog post](http://brandonlive.com/2010/02/21/measuring-memory-usage-in-windows-7))

**Comment by grosser** [comment]
you can try getting linguist working on that (the base of this repo ... or rebase this repo on linguist master .. but both are pretty complex things ... so good luck ;) )

**Comment by brendankehoe** [comment]
Thanks Michael. I put the code into a repository on Github but the language is not detected either. Would that be the same since Github uses linguist?

**Comment by grosser** [comment]
should be the same ... so open an issue with linguist I guess

**Comment by brendankehoe** [comment]
Thanks very much Michael. Very helpful
