### ISSUE TITLE
Usage problem

### ISSUE THREAD

**Issue by gameengineer** [grosser/language_sniffer#5]
I admit up front not knowing ruby but with google I've gotten your library to install and run.  However I may be using it wrong because I got results that were not expected.  My requirements are to run some sort of utility on files to determine their type so I am using cygwin file.exe.  However we also need to determine the programming language ASCII text files have.  Our in-house file transfer server needs to block text files that have code in them like C-sharp (.cs) files.  But people are clever and will simply change the file extension to get their source code to pass the server filter so we cannot just use extension checkers.  
It appears your library will do exactly what we need.   To test this app I used a cygwin console and ran it on a single .cs (csharp) text file.

$ ruby language_sniffer <C# filename> 

and it reported the number of lines, the extension and language.
However when I changed the extension from .cs to .cpp it then reported it as a C++ language.  If I removed the extension altogether it reported blank for extension and language.

I guess I thought it would scan the lines in the file trying to determine the programming language. Am I doing something wrong?

-Steve

**Comment by grosser** [comment]
it's doing lookups by extension/name/shebang line config is in https://github.com/grosser/language_sniffer/blob/master/lib/language_sniffer/languages.yml
